### ISSUE TITLE
As a lobby host I want to be able to create a lobby where I can choose from different game options and set a custom temporary username in order to create an instance of the game

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#1]
**Acceptance Criteria:**
- [x] After launching the game,  a "create game" - button is shown, on which a player can click
- [x] The player status will be automatically set to lobby host
- [x] After clicking on "create game" an interface "Menu setup" will be shown
- [x] Create and add "game settings", "custom Username" and "create lobby" to the interface, so one can chosse between them

**Development Tasks:**
- [x] sopra-fs22-group28/sopra-fs22-group28-client#1
- [x] sopra-fs22-group28/sopra-fs22-group28-client#2
- [x] sopra-fs22-group28/sopra-fs22-group28-client#3
- [x] sopra-fs22-group28/sopra-fs22-group28-client#4
- [x] sopra-fs22-group28/sopra-fs22-group28-server#30
- [x] sopra-fs22-group28/sopra-fs22-group28-client#51
- [x] sopra-fs22-group28/sopra-fs22-group28-client#50
- [x] sopra-fs22-group28/sopra-fs22-group28-server#113
- [x] sopra-fs22-group28/sopra-fs22-group28-server#114
- [x] #121
- [x] #123
- [x] #141

**Comment by tnaescher** [comment]
Development Tasks:
- [ ] Create Base SCSS / CSS Template according to designs
- [ ] Create View with a Button: "Create Game"
- [ ] Make "Create Game" Button redirect to new view: "Menu setup"
- [ ] Create "Menu setup" - view according to designs

**Comment by tnaescher** [comment]
Acceptance Criteria:
- [ ] After launching the game,  a "create game" - button is shown, on which a player can click
- [ ] The player status will be automatically set to lobby host
- [ ] After clicking on "create game" an interface "Menu setup" will be shown
- [ ] Create and add "game settings", "custom Username" and "create lobby" to the interface, so one can chosse between them

**Comment by tnaescher** [comment]
Completed
