### ISSUE TITLE
As a player, if the current round is taking too long, I want the round to automatically terminate after a defined time in order to avoid an infinite waiting for all the players

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#10]
**Acceptance Criteria:**
- [x] After the round starts a timer is initiated and if the timer hits zero, the round is automatically stopped for all the players and the users input is saved.
- [x] The timer can be set in the game settings

**Development Tasks:**
- [x] sopra-fs22-group28/sopra-fs22-group28-server#64
- [x] sopra-fs22-group28/sopra-fs22-group28-client#24
- [x] sopra-fs22-group28/sopra-fs22-group28-client#25
- [x] sopra-fs22-group28/sopra-fs22-group28-server#67

**Comment by tnaescher** [comment]
Omitted.
