### ISSUE TITLE
As a player after the round is done, I want to be able to see my and other peoples solutions in an overview page in order to see whether the other players have false, correct or the same solutions

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#11]
Acceptance Criteria:
- [x] After the round ends, the solutions of all players are bundled and an initial validity check has been called.
- [x] After each round the updated scoreboard is displayed on the screen
- [x] The validity check has to be done immediately after the round ends

Development Tasks: 
- [x] sopra-fs22-group28/sopra-fs22-group28-server#89
- [x] sopra-fs22-group28/sopra-fs22-group28-client#62
- [x] sopra-fs22-group28/sopra-fs22-group28-server#91
- [x] sopra-fs22-group28/sopra-fs22-group28-client#63
- [x] sopra-fs22-group28/sopra-fs22-group28-server#93
- [x] sopra-fs22-group28/sopra-fs22-group28-server#125
- [x] sopra-fs22-group28/sopra-fs22-group28-server#126
- [x] sopra-fs22-group28/sopra-fs22-group28-server#127
- [x] sopra-fs22-group28/sopra-fs22-group28-server#128
- [x] sopra-fs22-group28/sopra-fs22-group28-client#45
- [x] sopra-fs22-group28/sopra-fs22-group28-server#124
- [x] sopra-fs22-group28/sopra-fs22-group28-server#129
- [x] sopra-fs22-group28/sopra-fs22-group28-server#130
- [x] #152
- [x] #154

**Comment by tnaescher** [comment]
Completed
