### ISSUE TITLE
As a player I am able to press "ready" after the round in order to wait for the other players to be ready as well and start a new round

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#13]
**Acceptance Criteria:**
- [x] While the players wait for the letter to be chosen the new leaderboard will be shown
- [x] The “ready” button counts how many players are ready, if all pressed on it a new round starts.
- [x] Letters which already were played are omitted from the new draw.
- [x] The leaderboard shows how many points were given last round. name; points (+5)

**Development Tasks:**
- [x] sopra-fs22-group28/sopra-fs22-group28-client#28
- [x] sopra-fs22-group28/sopra-fs22-group28-client#29
- [x] sopra-fs22-group28/sopra-fs22-group28-client#30
- [x] sopra-fs22-group28/sopra-fs22-group28-client#27
- [x] sopra-fs22-group28/sopra-fs22-group28-server#138
- [x] sopra-fs22-group28/sopra-fs22-group28-server#139
- [x] sopra-fs22-group28/sopra-fs22-group28-client#60

**Comment by tnaescher** [comment]
Complete
