### ISSUE TITLE
As a player I want to be able to press on a “next game” button, which indicates that I want to play a new game after one game ends in order to play again

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#16]
**Acceptance Criteria:**
- [x] If all players hit this button, then automatically a new game will start.
-  [x] If just one person doesn’t want to play a next game then all players who are still in the lobby will be redirected to the lobby page.

**Development Task:**
- [x] sopra-fs22-group28/sopra-fs22-group28-client#32
- [x] sopra-fs22-group28/sopra-fs22-group28-client#31
- [x] sopra-fs22-group28/sopra-fs22-group28-server#36

**Comment by tnaescher** [comment]
Completed, Design has changed. Anyone can create a new game and invite the others now.
