### ISSUE TITLE
As a player I want to have a Chat-function in order to chat with the other players in between the rounds

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#17]
Acceptance Criteria:
- [x] The Chat should only be open in between the rounds, so no one can interrupt the others during the round.
- [x] During the round the chat function has to be hidden

Development Tasks:
- [x] sopra-fs22-group28/sopra-fs22-group28-server#97
- [x] sopra-fs22-group28/sopra-fs22-group28-server#98
- [x] sopra-fs22-group28/sopra-fs22-group28-client#66

**Comment by tnaescher** [comment]
Completed
