### ISSUE TITLE
As a Playerhost I want to be able to see information about the game before creating a lobby in order to understand the game and its functions

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#18]
Acceptance Criteria:
- [x] An information box should be available for the player by clicking on the information-symbol
- [x] The playerhost should fully understand the game by reading the information about the game

Development Tasks:
- [x] sopra-fs22-group28/sopra-fs22-group28-client#34
- [x] sopra-fs22-group28/sopra-fs22-group28-client#35
- [x] sopra-fs22-group28/sopra-fs22-group28-client#33
