### ISSUE TITLE
As a player I want to be able to see information about countries/rivers/cities in order to learn something about them

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#19]
Acceptance Criteria:
- [x] By clicking on a correct soultion the player gets information about the specific word on the screen
- [x] Only answers accepted by the system can be clicked on, not the voted ones
- [x] Each player can decide by his own if he wans to get information or not and it is possible only in between the rounds

Development Tasks:
- [x] sopra-fs22-group28/sopra-fs22-group28-server#100
- [x] sopra-fs22-group28/sopra-fs22-group28-client#65
- [x] sopra-fs22-group28/sopra-fs22-group28-server#102
- [x] sopra-fs22-group28/sopra-fs22-group28-server#136
- [x] sopra-fs22-group28/sopra-fs22-group28-server#137
