### ISSUE TITLE
As a playerhost I can create a category by myself in order to implement new ideas to categories

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#20]
Acceptance Criteria:
- [x] In the settings it should be able to create also an own category
- [x] The answers of the new category can only be validated through voting of the other players
- [x] If more than the half of the players accept the answers it will be accepted to get points

Development Tasks
- [x] sopra-fs22-group28/sopra-fs22-group28-client#61
- [x] sopra-fs22-group28/sopra-fs22-group28-server#104
- [x] sopra-fs22-group28/sopra-fs22-group28-server#105
- [x] sopra-fs22-group28/sopra-fs22-group28-client#70
