### ISSUE TITLE
As a lobby host I want to be able to modify the game settings in order to setup the game as desired

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#3]
**Acceptance Criteria:**
- [x] After clicking on "game settings" on the interface the fields "amount of players", "rounds", "round time" and "categories" will be shown
- [x] All fields have a dropdown-menu with predefined inputs a player can choose, only the "categories" have a list of predefined categories from which one can choose the wished ones
- [x] Enable edit of "amount of players", "rounds" and "round time" in "game settings"
- [x] The changes can be saved by clicking on save and the host will be redirected to the setup menu
- [x] If the host would not click on game settings, there will be a default setup, which is predefined if nothing has been changed

**Development Tasks:**

- [x] sopra-fs22-group28/sopra-fs22-group28-client#5
- [x] sopra-fs22-group28/sopra-fs22-group28-client#6
- [x] sopra-fs22-group28/sopra-fs22-group28-server#56
- [x] sopra-fs22-group28/sopra-fs22-group28-server#72
- [x] sopra-fs22-group28/sopra-fs22-group28-server#73
- [x] sopra-fs22-group28/sopra-fs22-group28-server#70
- [x] sopra-fs22-group28/sopra-fs22-group28-client#7
- [x] sopra-fs22-group28/sopra-fs22-group28-client#47
- [x] sopra-fs22-group28/sopra-fs22-group28-client#48
- [x] sopra-fs22-group28/sopra-fs22-group28-client#52
- [x] #145

**Comment by tnaescher** [comment]
All Tasks complete.
