### ISSUE TITLE
As a player I want to be able to join by pressing on an invite link in order to join the game

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#5]
**Acceptance Criteria:**
- [ ] After pressing on the invite link, the Player will be redirected to a setUsername interface, where he has to set a username, to be able to join the lobby.
- [ ] After pressing "join lobby" the user is directed to the lobby where he can see who else is also in the lobby
- [ ] If the input of the username is empty an error (notNull) will be shown with an advice to set the username

**Development Tasks:**
 - [ ] sopra-fs22-group28/sopra-fs22-group28-client#9
 - [ ] sopra-fs22-group28/sopra-fs22-group28-client#10
 - [ ] sopra-fs22-group28/sopra-fs22-group28-client#37
 - [x] sopra-fs22-group28/sopra-fs22-group28-server#68
