### ISSUE TITLE
As a player I can press on the “select a random letter” button, which will display a random letter on the screen in order to give out a random letter of the alphabet for the next round

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#7]
**Acceptance Criteria:**
- [x] After the game has started one random person will be able to press "select a random letter" and in a time of 4 seconds one letter will be chosen from the system and shown with an animation on the screen
- [x] Each round the next person clockwise will be able to press the "select a random letter"

**Development Tasks:**

- [x] sopra-fs22-group28/sopra-fs22-group28-client#13
- [x] sopra-fs22-group28/sopra-fs22-group28-client#14
- [x] sopra-fs22-group28/sopra-fs22-group28-server#23
- [x] #71
- [x] sopra-fs22-group28/sopra-fs22-group28-client#15
- [x] sopra-fs22-group28/sopra-fs22-group28-server#25
