### ISSUE TITLE
As a player I want to be able to add my solutions in a text field under each category in order to fill out all the categories with my solutions

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#8]
**Acceptance Criteria:**
- [x] The user can input his solutions in the textfield under each category
- [x] Each input has to start with the letter chosen for the round, otherwise the text will be marked in red and later not counted for the points

**Development Tasks:**
- [x] sopra-fs22-group28/sopra-fs22-group28-client#16
- [x] sopra-fs22-group28/sopra-fs22-group28-client#17
- [x] sopra-fs22-group28/sopra-fs22-group28-client#18
- [x] sopra-fs22-group28/sopra-fs22-group28-server#49
- [x] sopra-fs22-group28/sopra-fs22-group28-server#78
- [x] sopra-fs22-group28/sopra-fs22-group28-server#80
- [x] sopra-fs22-group28/sopra-fs22-group28-server#81
- [x] sopra-fs22-group28/sopra-fs22-group28-server#84
- [x] sopra-fs22-group28/sopra-fs22-group28-client#46
- [x] sopra-fs22-group28/sopra-fs22-group28-client#53
- [x] sopra-fs22-group28/sopra-fs22-group28-client#54
- [x] sopra-fs22-group28/sopra-fs22-group28-client#55
