### ISSUE TITLE
As a player, if I filled out all the text fields, I want to finish the current round by pressing on the “finish round” button in order to close the round for all players

### ISSUE THREAD

**Issue by wrozek** [sopra-fs22-group28/sopra-fs22-group28-server#9]
**Acceptance Criteria:**
- [x] The "finish round" button can be pressed if all the textfields are filled out otherwise the "finish round" button is not shown
- [x] After pressing "finish round" the round for all players will be closed and no one will be able to write more input
- [x] all the inputs written so far will be saved automatically
- [x]  a overview of all answers and points given will be shown to all users on the screen

**Development Tasks:**
- [x] sopra-fs22-group28/sopra-fs22-group28-client#19
- [x] sopra-fs22-group28/sopra-fs22-group28-client#20
- [x] sopra-fs22-group28/sopra-fs22-group28-client#21
- [x] sopra-fs22-group28/sopra-fs22-group28-client#22
- [x] sopra-fs22-group28/sopra-fs22-group28-client#23
- [x] sopra-fs22-group28/sopra-fs22-group28-server#63
- [x] #147
- [x] #148
